version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    labels:
      com.votingApp.environment: ${APP_ENV}
    links:
      - db
    env_file: ./app/.env
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    networks:
      - default

  db:
    image: mongo:3.4
    env_file: ./db/.env
    volumes:
      - "./utils/mongo/:/docker-entrypoint-initdb.d/"
      - dataVolume:/data/db
    networks:
      default:
        aliases:
          - db

volumes:
  dataVolume:

networks:
  default: